-- Enable the pgvector extension to work with embedding vectors
create extension if not exists vector;

-- Create a table to store simulation runs
create table if not exists public.simulation_results (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  circuit_id text not null,
  session_type text not null,
  total_laps integer not null,
  winner_driver_id text
);

-- Create a table to store driver results for each simulation
create table if not exists public.driver_results (
  id uuid default gen_random_uuid() primary key,
  simulation_id uuid references public.simulation_results(id) on delete cascade not null,
  driver_id text not null,
  team_id text not null,
  position integer not null,
  total_time float, -- Nullable if DNF
  points float default 0,
  tyre_compound text,
  strategy text -- e.g., "S-M-H"
);

-- Create a table to store detailed lap data (High Volume!)
-- Note: In a real production app, this might go to a time-series DB or storage bucket,
-- but for MVP, a table is fine.
create table if not exists public.lap_data (
  id bigint generated by default as identity primary key,
  driver_result_id uuid references public.driver_results(id) on delete cascade not null,
  lap_number integer not null,
  lap_time float not null,
  position integer not null,
  tyre_age integer,
  
  -- Compound index for fast retrieval of a specific lap or driver trace
  unique(driver_result_id, lap_number)
);

-- RLS (Row Level Security) Policies
-- Allow anyone with the Anon/Service key to READ
alter table public.simulation_results enable row level security;
create policy "Allow public read access" on public.simulation_results for select using (true);
create policy "Allow service insert" on public.simulation_results for insert with check (true);

alter table public.driver_results enable row level security;
create policy "Allow public read access" on public.driver_results for select using (true);
create policy "Allow service insert" on public.driver_results for insert with check (true);

alter table public.lap_data enable row level security;
create policy "Allow public read access" on public.lap_data for select using (true);
create policy "Allow service insert" on public.lap_data for insert with check (true);
